"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ObservationBatch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OBSERVATIONS_FIELD_NUMBER: builtins.int
    @property
    def observations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Observation]: ...
    def __init__(
        self,
        *,
        observations: collections.abc.Iterable[global___Observation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["observations", b"observations"]) -> None: ...

global___ObservationBatch = ObservationBatch

@typing.final
class Observation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    agent_id: builtins.int
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        agent_id: builtins.int = ...,
        inputs: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["agent_id", b"agent_id", "inputs", b"inputs"]) -> None: ...

global___Observation = Observation

@typing.final
class OutputBatch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OUTPUTS_FIELD_NUMBER: builtins.int
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Output]: ...
    def __init__(
        self,
        *,
        outputs: collections.abc.Iterable[global___Output] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["outputs", b"outputs"]) -> None: ...

global___OutputBatch = OutputBatch

@typing.final
class Output(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGENT_ID_FIELD_NUMBER: builtins.int
    ACTIONS_FIELD_NUMBER: builtins.int
    agent_id: builtins.int
    @property
    def actions(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    def __init__(
        self,
        *,
        agent_id: builtins.int = ...,
        actions: collections.abc.Iterable[builtins.float] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["actions", b"actions", "agent_id", b"agent_id"]) -> None: ...

global___Output = Output
