# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: FrameRequestClasses.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'FrameRequestClasses.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x46rameRequestClasses.proto\x12\x0bNNWebsocket\"\xa3\x01\n\x0c\x46rameRequest\x12/\n\x0bobservation\x18\x01 \x01(\x0b\x32\x18.NNWebsocket.ObservationH\x00\x12\'\n\x07\x66itness\x18\x02 \x01(\x0b\x32\x14.NNWebsocket.FitnessH\x00\x12\x32\n\rtrain_request\x18\x03 \x01(\x0b\x32\x19.NNWebsocket.TrainRequestH\x00\x42\x05\n\x03msg\"\x1d\n\x0bObservation\x12\x0e\n\x06inputs\x18\x01 \x03(\x02\"\x19\n\x06\x41\x63tion\x12\x0f\n\x07outputs\x18\x01 \x03(\x02\"\x19\n\x07\x46itness\x12\x0e\n\x06values\x18\x01 \x03(\x02\"d\n\x0cTrainRequest\x12-\n\x0bobservation\x18\x01 \x03(\x0b\x32\x18.NNWebsocket.Observation\x12%\n\x07\x66itness\x18\x02 \x03(\x0b\x32\x14.NNWebsocket.FitnessB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FrameRequestClasses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_FRAMEREQUEST']._serialized_start=43
  _globals['_FRAMEREQUEST']._serialized_end=206
  _globals['_OBSERVATION']._serialized_start=208
  _globals['_OBSERVATION']._serialized_end=237
  _globals['_ACTION']._serialized_start=239
  _globals['_ACTION']._serialized_end=264
  _globals['_FITNESS']._serialized_start=266
  _globals['_FITNESS']._serialized_end=291
  _globals['_TRAINREQUEST']._serialized_start=293
  _globals['_TRAINREQUEST']._serialized_end=393
# @@protoc_insertion_point(module_scope)
