# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: neural_network.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'neural_network.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14neural_network.proto\x12\x0cnn_websocket\"\xf4\x02\n\x13NeuralNetworkConfig\x12\x14\n\x0cnum_networks\x18\x01 \x01(\x05\x12\x12\n\nnum_inputs\x18\x02 \x01(\x05\x12\x13\n\x0bnum_outputs\x18\x03 \x01(\x05\x12\x1a\n\x12hidden_layer_sizes\x18\x04 \x03(\x05\x12\x13\n\x0bweights_min\x18\x05 \x01(\x02\x12\x13\n\x0bweights_max\x18\x06 \x01(\x02\x12\x10\n\x08\x62ias_min\x18\x07 \x01(\x02\x12\x10\n\x08\x62ias_max\x18\x08 \x01(\x02\x12:\n\x10input_activation\x18\t \x01(\x0e\x32 .nn_websocket.ActivationFunction\x12;\n\x11hidden_activation\x18\n \x01(\x0e\x32 .nn_websocket.ActivationFunction\x12;\n\x11output_activation\x18\x0b \x01(\x0e\x32 .nn_websocket.ActivationFunction*7\n\x12\x41\x63tivationFunction\x12\n\n\x06LINEAR\x10\x00\x12\x08\n\x04RELU\x10\x01\x12\x0b\n\x07SIGMOID\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'neural_network_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACTIVATIONFUNCTION']._serialized_start=413
  _globals['_ACTIVATIONFUNCTION']._serialized_end=468
  _globals['_NEURALNETWORKCONFIG']._serialized_start=39
  _globals['_NEURALNETWORKCONFIG']._serialized_end=411
# @@protoc_insertion_point(module_scope)
