# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: NNWebsocketClasses.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'NNWebsocketClasses.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import NeuralNetwork_pb2 as _NeuralNetwork_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18NNWebsocketClasses.proto\x12\x0bNNWebsocket\x1a\x13NeuralNetwork.proto\"\xb1\x03\n\x13NeuralNetworkConfig\x12\x12\n\nnum_inputs\x18\x01 \x01(\x05\x12\x13\n\x0bnum_outputs\x18\x02 \x01(\x05\x12\x1a\n\x12hidden_layer_sizes\x18\x03 \x03(\x05\x12\x13\n\x0bweights_min\x18\x04 \x01(\x02\x12\x13\n\x0bweights_max\x18\x05 \x01(\x02\x12\x10\n\x08\x62ias_min\x18\x06 \x01(\x02\x12\x10\n\x08\x62ias_max\x18\x07 \x01(\x02\x12?\n\x10input_activation\x18\x08 \x01(\x0e\x32%.NeuralNetwork.ActivationFunctionData\x12@\n\x11hidden_activation\x18\t \x01(\x0e\x32%.NeuralNetwork.ActivationFunctionData\x12@\n\x11output_activation\x18\n \x01(\x0e\x32%.NeuralNetwork.ActivationFunctionData\x12\x34\n\toptimizer\x18\x0b \x01(\x0b\x32\x1c.NeuralNetwork.OptimizerDataH\x00\x88\x01\x01\x42\x0c\n\n_optimizer\"\x93\x01\n\rConfiguration\x12;\n\x0eneuroevolution\x18\x01 \x01(\x0b\x32!.NNWebsocket.NeuroevolutionConfigH\x00\x12>\n\x10\x66itness_approach\x18\x02 \x01(\x0b\x32\".NNWebsocket.FitnessApproachConfigH\x00\x42\x05\n\x03msg\"H\n\x16GeneticAlgorithmConfig\x12\x17\n\x0fpopulation_size\x18\x01 \x01(\x05\x12\x15\n\rmutation_rate\x18\x02 \x01(\x02\"\x90\x01\n\x14NeuroevolutionConfig\x12\x38\n\x0eneural_network\x18\x01 \x01(\x0b\x32 .NNWebsocket.NeuralNetworkConfig\x12>\n\x11genetic_algorithm\x18\x02 \x01(\x0b\x32#.NNWebsocket.GeneticAlgorithmConfig\"Q\n\x15\x46itnessApproachConfig\x12\x38\n\x0eneural_network\x18\x01 \x01(\x0b\x32 .NNWebsocket.NeuralNetworkConfigB\x02H\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'NNWebsocketClasses_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'H\003'
  _globals['_NEURALNETWORKCONFIG']._serialized_start=63
  _globals['_NEURALNETWORKCONFIG']._serialized_end=496
  _globals['_CONFIGURATION']._serialized_start=499
  _globals['_CONFIGURATION']._serialized_end=646
  _globals['_GENETICALGORITHMCONFIG']._serialized_start=648
  _globals['_GENETICALGORITHMCONFIG']._serialized_end=720
  _globals['_NEUROEVOLUTIONCONFIG']._serialized_start=723
  _globals['_NEUROEVOLUTIONCONFIG']._serialized_end=867
  _globals['_FITNESSAPPROACHCONFIG']._serialized_start=869
  _globals['_FITNESSAPPROACHCONFIG']._serialized_end=950
# @@protoc_insertion_point(module_scope)
